[package]
name = "plasm-runtime"
version = "1.8.0"
authors = ["Stake Technologies <devops@stake.co.jp>"]
edition = "2018"
build = "build.rs"

[dependencies]
# third-party dependencies
serde = { version = "1.0.106", optional = true }
codec = { package = "parity-scale-codec", version = "2.0", default-features = false, features = ["derive"] }
lazy_static = { version = "1.4", optional = true }
hex-literal = { version = "0.2", optional = true }

# primitives
plasm-primitives = { path = "../primitives", default-features = false }
sp-core = { version = "3.0.0", default-features = false }
sp-io = { version = "3.0.0", default-features = false }
sp-runtime = { version = "3.0.0", default-features = false }
sp-runtime-interface = { version = "3.0.0", default-features = false }
sp-consensus-babe = { version = "0.9.0", default-features = false }
sp-offchain = { version = "3.0.0", default-features = false }
sp-api = { version = "3.0.0", default-features = false }
sp-inherents = { version = "3.0.0", default-features = false }
sp-block-builder = { version = "3.0.0", default-features = false }
sp-transaction-pool = { version = "3.0.0", default-features = false }
sp-std = { version = "3.0.0", default-features = false }
sp-version = { version = "3.0.0", default-features = false }
sp-session = { version = "3.0.0", default-features = false }
sp-authority-discovery = {default-features = false, version = '3.0.0'}
sp-staking = { default-features = false, version = '3.0.0' }

# frame dependencies
#pallet-contract-operator = { path = "../../../frame/operator", default-features = false }
#pallet-operator-trading = { path = "../../../frame/trading", default-features = false }
#pallet-dapps-staking = { path = "../../../frame/dapps-staking", default-features = false }
pallet-plasm-rewards = { path = "../../../frame/plasm-rewards", default-features = false }
pallet-plasm-validator = { path = "../../../frame/plasm-validator", default-features = false }
pallet-custom-signatures = { path = "../../../frame/custom-signatures", default-features = false }
#pallet-ovm = { path = "../../../frame/ovm", default-features = false }
#pallet-plasma = { path = "../../../frame/plasma", default-features = false }
pallet-evm = { path = "../../../vendor/frontier/frame/evm", default-features = false }
pallet-evm-precompile-simple = { path = "../../../vendor/frontier/frame/evm/precompile/simple", default-features = false }
frame-executive = { version = "3.0.0", default-features = false }
pallet-balances = { version = "3.0.0", default-features = false }
pallet-contracts = { version = "3.0.0", default-features = false }
pallet-contracts-primitives = { version = "3.0.0", default-features = false }
pallet-contracts-rpc-runtime-api = { version = "3.0.0", default-features = false }
pallet-grandpa = { version = "3.0.0", default-features = false }
pallet-indices = { version = "3.0.0", default-features = false }
pallet-nicks = { version = "3.0.0", default-features = false }
pallet-randomness-collective-flip = { version = "3.0.0", default-features = false }
pallet-scheduler = { version = "3.0.0", default-features = false }
pallet-sudo = { version = "3.0.0", default-features = false }
frame-support = { version = "3.0.0", default-features = false }
frame-system = { version = "3.0.0", default-features = false }
frame-system-rpc-runtime-api = { version = "3.0.0", default-features = false }
pallet-timestamp = { version = "3.0.0", default-features = false }
pallet-transaction-payment = { version = "3.0.0", default-features = false }
pallet-transaction-payment-rpc-runtime-api = { version = "3.0.0", default-features = false }
pallet-utility = { version = "3.0.0", default-features = false }
fp-rpc = { path = "../../../vendor/frontier/primitives/rpc", default-features = false }
pallet-ethereum = { path = "../../../vendor/frontier/frame/ethereum", default-features = false }
getrandom = { version = "0.2", features = ["js"] }

# Staking dependencies
pallet-authority-discovery = {default-features = false, version = '3.0.0'}
pallet-authorship = {default-features = false, version = '3.0.0'}
pallet-babe = {default-features = false, version = '3.0.0'}
pallet-collective = {default-features = false, version = '3.0.0'}
pallet-elections-phragmen = {default-features = false, version = '3.0.0'}
pallet-im-online = {default-features = false, version = '3.0.0'}
pallet-offences = {default-features = false, version = '3.0.0'}
pallet-session = {default-features = false, version = '3.0.0'}
pallet-plasm-staking = { path = "../../../frame/plasm-staking", default-features = false }
pallet-plasm-staking-rewards = { path = "../../../frame/plasm-staking-rewards", default-features = false }
pallet-treasury = {default-features = false, version = '3.0.0'}
pallet-bounties = {default-features = false, version = '3.0.0'}
pallet-tips = {default-features = false, version = '3.0.0'}


[build-dependencies]
substrate-wasm-builder = "4.0.0"

[features]
default = ["std"]
std = [
    "serde",
    "codec/std",
    "lazy_static",
    "hex-literal",
    "sp-api/std",
    "sp-block-builder/std",
    "sp-core/std",
    "sp-io/std",
    "sp-consensus-babe/std",
    "sp-staking/std",
    "sp-authority-discovery/std",
    "sp-runtime/std",
    "sp-runtime-interface/std",
    "sp-session/std",
    "sp-std/std",
    "sp-version/std",
    "sp-transaction-pool/std",
    "sp-inherents/std",
    "sp-offchain/std",
    "plasm-primitives/std",
    "frame-support/std",
    "frame-executive/std",
    "frame-system/std",
    "frame-system-rpc-runtime-api/std",
    "fp-rpc/std",
    "pallet-authorship/std",
    "pallet-babe/std",
    "pallet-balances/std",
    "pallet-contracts/std",
    "pallet-contracts-primitives/std",
    "pallet-contracts-rpc-runtime-api/std",
    "pallet-evm/std",
    "pallet-evm-precompile-simple/std",
    "pallet-grandpa/std",
    "pallet-indices/std",
    "pallet-im-online/std",
    "pallet-nicks/std",
    "pallet-custom-signatures/std",
    "pallet-plasm-rewards/std",
    "pallet-plasm-validator/std",
#    "pallet-plasma/std",
    "pallet-randomness-collective-flip/std",
    "pallet-scheduler/std",
    "pallet-session/std",
#    "pallet-contract-operator/std",
#    "pallet-operator-trading/std",
#    "pallet-dapps-staking/std",
    "pallet-ethereum/std",
    "pallet-sudo/std",
    "pallet-timestamp/std",
    "pallet-transaction-payment/std",
    "pallet-transaction-payment-rpc-runtime-api/std",
    "pallet-utility/std",
    "pallet-offences/std",
#    "pallet-ovm/std",
    "pallet-collective/std",
    "pallet-plasm-staking/std",
    "pallet-plasm-staking-rewards/std",
    "pallet-treasury/std",
    "pallet-bounties/std",
    "pallet-tips/std"
]
